version: '2.1'

services:

  node_vue:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ionic-vue-2/front
    volumes:
      - ./:/src
      - nodemodules:/src/node_modules
    ports:
      - 8100:8100

volumes:
    nodemodules: {}